version: '3.8'

services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - devops-network
  spring:
    restart: on-failure
    container_name: spring
    depends_on:
      - db
    image: ghassendhif/ghassendhif-5sim1-g5
    ports:
      - "8082:8082"
    networks:
      - devops-network
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  devops-network:
    driver: bridge